const fieldMap = {
  surat_keterangan_domisili: [
    {
      name: "nik",
      label: "NIK (Nomor Induk Kependudukan)",
      type: "search",
      required: true,
      placeholder: "Value",
    },
    {
      name: "nama_lengkap",
      label: "Nama",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "tempat_lahir",
      label: "Tempat Lahir",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "tgl_lahir",
      label: "Tanggal Lahir",
      type: "date",
      required: true,
      placeholder: "Value",
    },
    {
      name: "agama",
      label: "Agama",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "status_kawin",
      label: "Status Pernikahan",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "kewarganegaraan",
      label: "Kewarganegaraan",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    // {
    //   name: "jenis_pekerjaan",
    //   label: "Pekerjaan",
    //   type: "select",
    //   required: true,
    //   placeholder: "Value",
    //   options: [
    //     { value: "pegawai_negeri", label: "Pegawai Negeri" },
    //     { value: "pegawai_swasta", label: "Pegawai Swasta" },
    //     { value: "wiraswasta", label: "Wiraswasta" },
    //     { value: "pelajar", label: "Pelajar/Mahasiswa" },
    //     { value: "ibu_rumah_tangga", label: "Ibu Rumah Tangga" },
    //   ],
    // }
    {
      name: "jenis_pekerjaan",
      label: "Pekerjaan",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    ,
    {
      name: "alamat_lengkap",
      label: "Alamat",
      type: "long_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "tgl_domisili",
      label: "Tanggal Domisili",
      type: "date",
      required: true,
      placeholder: "Value",
    },
    {
      name: "alamat_domisili",
      label: "Alamat Domisili",
      type: "long_answer",
      required: true,
      placeholder: "Value",
    },

    {
      name: "tanggal_surat",
      label: "Tanggal Surat",
      type: "date_now",
      required: true,
      placeholder: "Value",
    },
  ],

  surat_pengantar_desa: [
    {
      name: "nik",
      label: "NIK (Nomor Induk Kependudukan)",
      type: "search",
      required: true,
      placeholder: "Value",
    },
    {
      name: "nama_lengkap",
      label: "Nama",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "tempat_lahir",
      label: "Tempat Lahir",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "tgl_lahir",
      label: "Tanggal Lahir",
      type: "date",
      required: true,
      placeholder: "Value",
    },
    {
      name: "agama",
      label: "Agama",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "status_kawin",
      label: "Status Pernikahan",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "kewarganegaraan",
      label: "Kewarganegaraan",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    // {
    //   name: "jenis_pekerjaan",
    //   label: "Pekerjaan",
    //   type: "select",
    //   required: true,
    //   placeholder: "Value",
    //   options: [
    //     { value: "pegawai_negeri", label: "Pegawai Negeri" },
    //     { value: "pegawai_swasta", label: "Pegawai Swasta" },
    //     { value: "wiraswasta", label: "Wiraswasta" },
    //     { value: "pelajar", label: "Pelajar/Mahasiswa" },
    //     { value: "ibu_rumah_tangga", label: "Ibu Rumah Tangga" },
    //   ],
    // },
    {
      name: "jenis_pekerjaan",
      label: "Pekerjaan",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "alamat_lengkap",
      label: "Alamat",
      type: "long_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "maksud",
      label: "Maksud",
      type: "long_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "tanggal_surat",
      label: "Tanggal Surat",
      type: "date_now",
      required: true,
      placeholder: "Value",
    },
  ],

  surat_keterangan_usaha: [
    {
      name: "nik",
      label: "NIK (Nomor Induk Kependudukan)",
      type: "search",
      required: true,
      placeholder: "Value",
    },
    {
      name: "nama_lengkap",
      label: "Nama",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "tempat_lahir",
      label: "Tempat Lahir",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "tgl_lahir",
      label: "Tanggal Lahir",
      type: "date",
      required: true,
      placeholder: "Value",
    },

    {
      name: "alamat_lengkap",
      label: "Alamat",
      type: "long_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "nomor_hp",
      label: "Nomor HP",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "klasifikasi_usaha",
      label: "Klasifikasi Usaha",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "jenis_usaha",
      label: "Jenis Usaha",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "nama_usaha",
      label: "Nama Usaha",
      type: "short_answer",
      required: true,
      placeholder: "Value",
    },
    {
      name: "tanggal_surat",
      label: "Tanggal Surat",
      type: "date_now",
      required: true,
      placeholder: "Value",
    },
  ],
};

export default fieldMap;
